# version: '3'

services:

  # create and setup postgresql database
  db:
    # profiles: ['db','all']
    image: postgres:latest
    restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_DB: donations
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data

  # create and setup Flyway for managing migrations/seed-data
  flyway:
    # profiles: ['db','all']
    image: flyway/flyway
    command: -url=jdbc:postgresql://db/donations -schemas=public -user=postgres
      -password=password -connectRetries=5 migrate
    volumes:
      - ./database:/flyway/sql
    depends_on:
      - db

  # Express API container
  api:
    profiles: ['api','all']
    image: express-api
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./server:/app
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/donations?schema=public"

volumes:
  db: